version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - ui
      - api
  ui:
    image: node:22
    working_dir: /app/ui
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./ui:/app/ui
  api:
    image: receep:latest
    build:
      context: api
    working_dir: /app/api
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: ./start.sh
    volumes:
      - ./api:/app/api
      - ./mnt/data:/data
      - ./mnt/log:/var/log/receep/api
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb #shared memory size
    env_file:
      - .env
    # ports:
    #   - "5432:5432" # only for debugging purposes 
    volumes:
      - ./mnt/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5

  # TODO: backup cron job
