version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - ui
      - api
  ui:
    image: node:22
    working_dir: /app/ui
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./ui:/app/ui
  api:
    image: divvy:latest
    build:
      context: api
    working_dir: /app/api
    stop_signal: SIGINT # https://github.com/docker/compose/issues/4199#issuecomment-426109482
    command: uvicorn main:fastapi_app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/app/api
      - ./mnt/data:/data
      - ./mnt/log:/var/log/divvy/api
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb #shared memory size
    env_file:
      - .env
    volumes:
      # - ./db/initdb.d:/docker-entrypoint-initdb.d/:ro # TODO: still need this, when SQLAlchemy is there?
      - ./mnt/data/postgres:/var/lib/postgresql/data

  # TODO: backup cron job
